### PR TITLE
Next process moving

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems still not starting https://github.com/symplify/coding-standard/blob/main/.github/workflows/code_analysis.yaml

**Comment by TomasVotruba** [comment]
For some reason, it was disabled in the settings. Now it's on :heavy_check_mark:

**Comment by samsonasik** [comment]
Thank you, it starting now 👍

**Comment by samsonasik** [comment]
Let's try

**Comment by samsonasik** [comment]
Released https://github.com/symplify/coding-standard/releases/tag/11.1.26.72, let's try in getrector.org

**Pull request merged**
